/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as UsersImport } from './routes/users'
import { Route as UpdatesImport } from './routes/updates'
import { Route as NewsImport } from './routes/news'
import { Route as IndexImport } from './routes/index'
import { Route as NewsletterNameImport } from './routes/newsletter.$name'

// Create/Update Routes

const UsersRoute = UsersImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => rootRoute,
} as any)

const UpdatesRoute = UpdatesImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRoute,
} as any)

const NewsRoute = NewsImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const NewsletterNameRoute = NewsletterNameImport.update({
  id: '/newsletter/$name',
  path: '/newsletter/$name',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsImport
      parentRoute: typeof rootRoute
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesImport
      parentRoute: typeof rootRoute
    }
    '/users': {
      id: '/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof UsersImport
      parentRoute: typeof rootRoute
    }
    '/newsletter/$name': {
      id: '/newsletter/$name'
      path: '/newsletter/$name'
      fullPath: '/newsletter/$name'
      preLoaderRoute: typeof NewsletterNameImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/updates': typeof UpdatesRoute
  '/users': typeof UsersRoute
  '/newsletter/$name': typeof NewsletterNameRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/updates': typeof UpdatesRoute
  '/users': typeof UsersRoute
  '/newsletter/$name': typeof NewsletterNameRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/news': typeof NewsRoute
  '/updates': typeof UpdatesRoute
  '/users': typeof UsersRoute
  '/newsletter/$name': typeof NewsletterNameRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/news' | '/updates' | '/users' | '/newsletter/$name'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/news' | '/updates' | '/users' | '/newsletter/$name'
  id: '__root__' | '/' | '/news' | '/updates' | '/users' | '/newsletter/$name'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  NewsRoute: typeof NewsRoute
  UpdatesRoute: typeof UpdatesRoute
  UsersRoute: typeof UsersRoute
  NewsletterNameRoute: typeof NewsletterNameRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  NewsRoute: NewsRoute,
  UpdatesRoute: UpdatesRoute,
  UsersRoute: UsersRoute,
  NewsletterNameRoute: NewsletterNameRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/news",
        "/updates",
        "/users",
        "/newsletter/$name"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/news": {
      "filePath": "news.tsx"
    },
    "/updates": {
      "filePath": "updates.tsx"
    },
    "/users": {
      "filePath": "users.tsx"
    },
    "/newsletter/$name": {
      "filePath": "newsletter.$name.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
